/**
 * Session Routes
 * Handles session data operations
 */

import { Router, Request, Response } from 'express';
import { sessionRepository } from '../../../shared/dist/src/repositories/sessionRepository.js';
import { Session, MessageLog, AudioChunk } from '../../../shared/dist/src/types/index.js';

const router = Router();

/**
 * Get all sessions for a user
 */
router.get('/user/:userId', async (req: Request, res: Response) => {
  try {
    const { userId } = req.params;

    if (!userId) {
      return res.status(400).json({ error: 'User ID is required' });
    }

    const sessions = await sessionRepository.getAll(userId);
    res.json({ sessions });
  } catch (error) {
    console.error('Error getting sessions:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to get sessions';
    res.status(500).json({ error: errorMessage });
  }
});

/**
 * Get session by ID
 */
router.get('/:sessionId/user/:userId', async (req: Request, res: Response) => {
  try {
    const { sessionId, userId } = req.params;

    if (!sessionId || !userId) {
      return res.status(400).json({ error: 'Session ID and User ID are required' });
    }

    const session = await sessionRepository.getById(userId, sessionId);

    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    res.json({ session });
  } catch (error) {
    console.error('Error getting session:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to get session';
    res.status(500).json({ error: errorMessage });
  }
});

/**
 * Create a new session
 */
router.post('/user/:userId', async (req: Request, res: Response) => {
  try {
    const { userId } = req.params;
    const { transcript, durationSeconds, audioChunks } = req.body;

    if (!userId) {
      return res.status(400).json({ error: 'User ID is required' });
    }

    if (!transcript || !Array.isArray(transcript)) {
      return res.status(400).json({ error: 'Transcript is required and must be an array' });
    }

    if (typeof durationSeconds !== 'number' || durationSeconds < 0) {
      return res.status(400).json({ error: 'Duration must be a non-negative number' });
    }

    // Create session object
    const session: Session = {
      id: '', // Will be generated by repository
      date: new Date().toISOString(),
      durationSeconds,
      preview: transcript[0]?.text?.substring(0, 100) || 'New session',
      transcript: transcript as MessageLog[],
      audioChunks: audioChunks as AudioChunk[] | undefined,
    };

    const savedSession = await sessionRepository.save(userId, session);
    res.json({ session: savedSession });
  } catch (error) {
    console.error('Error creating session:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to create session';
    res.status(500).json({ error: errorMessage });
  }
});

/**
 * Update a session
 */
router.put('/:sessionId/user/:userId', async (req: Request, res: Response) => {
  try {
    const { sessionId, userId } = req.params;
    const updates = req.body;

    if (!sessionId || !userId) {
      return res.status(400).json({ error: 'Session ID and User ID are required' });
    }

    const updatedSession = await sessionRepository.update(userId, sessionId, updates);

    if (!updatedSession) {
      return res.status(404).json({ error: 'Session not found' });
    }

    res.json({ session: updatedSession });
  } catch (error) {
    console.error('Error updating session:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to update session';
    res.status(500).json({ error: errorMessage });
  }
});

/**
 * Delete a session
 */
router.delete('/:sessionId/user/:userId', async (req: Request, res: Response) => {
  try {
    const { sessionId, userId } = req.params;

    if (!sessionId || !userId) {
      return res.status(400).json({ error: 'Session ID and User ID are required' });
    }

    const deleted = await sessionRepository.delete(userId, sessionId);

    if (!deleted) {
      return res.status(404).json({ error: 'Session not found' });
    }

    res.json({ success: true });
  } catch (error) {
    console.error('Error deleting session:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to delete session';
    res.status(500).json({ error: errorMessage });
  }
});

export { router as sessionRoutes };

