/**
 * Session Routes
 * Handles session data operations
 */

import { Router, Request, Response } from 'express';
import { sessionRepository } from '../../../shared/dist/src/repositories/sessionRepository.js';
import { Session, MessageLog, AudioChunk } from '../../../shared/dist/src/types/index.js';
import { logger } from '../utils/logger.js';

const router = Router();

/**
 * Get all sessions for a user
 */
router.get('/user/:userId', async (req: Request, res: Response) => {
  try {
    const { userId } = req.params;

    if (!userId) {
      return res.status(400).json({ error: 'User ID is required' });
    }

    const sessions = await sessionRepository.getAll(userId);
    res.json({ sessions });
  } catch (error) {
    const userIdFromParams = req.params.userId;
    logger.error(
      'Error getting sessions',
      { userId: userIdFromParams },
      error instanceof Error ? error : undefined
    );
    res.status(500).json({ error: "We couldn't load your conversations. Please try again." });
  }
});

/**
 * Get session by ID
 */
router.get('/:sessionId/user/:userId', async (req: Request, res: Response) => {
  try {
    const { sessionId, userId } = req.params;

    if (!sessionId || !userId) {
      return res.status(400).json({ error: 'Session ID and User ID are required' });
    }

    const session = await sessionRepository.getById(userId, sessionId);

    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    res.json({ session });
  } catch (error) {
    const userIdFromParams = req.params.userId;
    const sessionIdFromParams = req.params.sessionId;
    logger.error(
      'Error getting session',
      { userId: userIdFromParams, sessionId: sessionIdFromParams },
      error instanceof Error ? error : undefined
    );
    res.status(500).json({ error: "We couldn't load this conversation. Please try again." });
  }
});

/**
 * Create a new session
 */
router.post('/user/:userId', async (req: Request, res: Response) => {
  try {
    const { userId } = req.params;
    const { transcript, durationSeconds, audioChunks } = req.body;

    if (!userId) {
      return res.status(400).json({ error: 'User ID is required' });
    }

    if (!transcript || !Array.isArray(transcript)) {
      return res.status(400).json({ error: 'Transcript is required and must be an array' });
    }

    if (typeof durationSeconds !== 'number' || durationSeconds < 0) {
      return res.status(400).json({ error: 'Duration must be a non-negative number' });
    }

    // Validate payload size before processing
    const payloadSize = JSON.stringify(req.body).length;
    const maxSize = 50 * 1024 * 1024; // 50MB
    if (payloadSize > maxSize) {
      logger.warn('Session payload too large, omitting audio', {
        userId,
        payloadSizeMB: (payloadSize / 1024 / 1024).toFixed(2),
      });
      // If audio chunks are too large, save session without audio
      const session: Session = {
        id: '',
        date: new Date().toISOString(),
        durationSeconds,
        preview: transcript[0]?.text?.substring(0, 100) || 'New session',
        transcript: transcript as MessageLog[],
        // Omit audioChunks if payload is too large
        audioChunks: undefined,
      };
      const savedSession = await sessionRepository.save(userId, session);
      return res.json({
        session: savedSession,
        warning: 'Audio chunks were too large and were not saved. Session saved without audio.',
      });
    }

    // Create session object
    const session: Session = {
      id: '', // Will be generated by repository
      date: new Date().toISOString(),
      durationSeconds,
      preview: transcript[0]?.text?.substring(0, 100) || 'New session',
      transcript: transcript as MessageLog[],
      audioChunks: audioChunks as AudioChunk[] | undefined,
    };

    const savedSession = await sessionRepository.save(userId, session);
    logger.info('Session created successfully', {
      userId,
      sessionId: savedSession?.id,
      durationSeconds,
    });
    res.json({ session: savedSession });
  } catch (error) {
    const userIdFromParams = req.params.userId;
    const durationSecondsFromBody = (req.body as { durationSeconds?: number })?.durationSeconds;
    logger.error(
      'Error creating session',
      { userId: userIdFromParams, durationSeconds: durationSecondsFromBody },
      error instanceof Error ? error : undefined
    );
    res.status(500).json({ error: "We couldn't save your conversation. Please try again." });
  }
});

/**
 * Update a session
 */
router.put('/:sessionId/user/:userId', async (req: Request, res: Response) => {
  try {
    const { sessionId, userId } = req.params;
    const updates = req.body;

    if (!sessionId || !userId) {
      return res.status(400).json({ error: 'Session ID and User ID are required' });
    }

    const updatedSession = await sessionRepository.update(userId, sessionId, updates);

    if (!updatedSession) {
      return res.status(404).json({ error: 'Session not found' });
    }

    logger.info('Session updated successfully', { userId, sessionId });
    res.json({ session: updatedSession });
  } catch (error) {
    const userIdFromParams = req.params.userId;
    const sessionIdFromParams = req.params.sessionId;
    logger.error(
      'Error updating session',
      { userId: userIdFromParams, sessionId: sessionIdFromParams },
      error instanceof Error ? error : undefined
    );
    res.status(500).json({ error: "We couldn't update your conversation. Please try again." });
  }
});

/**
 * Delete a session
 */
router.delete('/:sessionId/user/:userId', async (req: Request, res: Response) => {
  try {
    const { sessionId, userId } = req.params;

    if (!sessionId || !userId) {
      return res.status(400).json({ error: 'Session ID and User ID are required' });
    }

    const deleted = await sessionRepository.delete(userId, sessionId);

    if (!deleted) {
      return res.status(404).json({ error: 'Session not found' });
    }

    logger.info('Session deleted successfully', { userId, sessionId });
    res.json({ success: true });
  } catch (error) {
    const userIdFromParams = req.params.userId;
    const sessionIdFromParams = req.params.sessionId;
    logger.error(
      'Error deleting session',
      { userId: userIdFromParams, sessionId: sessionIdFromParams },
      error instanceof Error ? error : undefined
    );
    res.status(500).json({ error: "We couldn't delete this conversation. Please try again." });
  }
});

export { router as sessionRoutes };
